name: Daily scrape Njuskalo's cars

on:
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Daily Job
        env:
          SECRET_KEY: ${{ secrets.AUTHORIZATION_KEY }}
        run: python njuskalo_scraper.py

      - name: Commit data
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git status
            git add cars_detail.db
            git commit -m "Update cars_detail.db"
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
