name: Daily scrape Njuskalo's cars

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Pipenv
        run: |
          pip install pipenv

      - name: Install dependencies with Pipenv
        run: |
          pipenv install --deploy --ignore-pipfile

      - name: Run Daily Scraping Job
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: pipenv run python source/njuskalo_scraper.py

      - name: Run Sending Email Job
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          DB_ENCRYPTION_KEY: ${{ secrets.DB_ENCRYPTION_KEY }}
        run: pipenv run python source/summarize_cars.py
