name: Daily scrape Njuskalo's car

on:
  schedule:
    - cron: '0 22 * * *'

jobs:
  run_daily_job:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.AUTHORIZATION_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Daily Job
        run: python njuskalo_scraper.py
        env:
          SECRET_KEY: ${{ secrets.AUTHORIZATION_KEY }}
